## Deliverable 2. Create a Customer Travel Destinations Map.

In [15]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [16]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,0,Mwinilunga,-11.7358,24.4293,60.67,96,83,1.01,ZM,2022-04-06 00:40:27,broken clouds
1,1,Jamestown,42.0970,-79.2353,55.04,48,0,6.91,US,2022-04-06 00:36:01,clear sky
2,2,Sangar,63.9242,127.4739,1.65,93,100,4.92,RU,2022-04-06 00:40:28,overcast clouds
3,3,Kaitangata,-46.2817,169.8464,54.19,64,60,20.18,NZ,2022-04-06 00:40:28,broken clouds
4,4,Tiksi,71.6872,128.8694,-10.43,100,100,3.40,RU,2022-04-06 00:40:28,overcast clouds

In [17]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [18]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
6,6,La Palma,33.8464,-118.0467,86.67,65,0,10.36,US,2022-04-06 00:40:29,clear sky
14,14,The Valley,18.2170,-63.0578,78.82,76,17,17.78,AI,2022-04-06 00:40:31,few clouds
15,15,Maragogi,-9.0122,-35.2225,77.32,84,66,4.54,BR,2022-04-06 00:40:03,broken clouds
16,16,Qui Nhon,13.7667,109.2333,76.17,80,100,19.26,VN,2022-04-06 00:40:31,overcast clouds
22,22,Puerto Ayora,-0.7393,-90.3518,78.06,86,25,7.09,EC,2022-04-06 00:40:33,scattered clouds
28,28,Kaeo,-35.1000,173.7833,79.32,74,21,10.78,NZ,2022-04-06 00:40:34,few clouds
32,32,Poum,-20.2333,164.0167,80.53,89,100,39.10,NC,2022-04-06 00:40:36,moderate rain
36,36,Sarh,9.1429,18.3923,83.52,45,98,7.36,TD,2022-04-06 00:40:37,overcast clouds
40,40,Isangel,-19.5500,169.2667,84.31,79,100,4.61,VU,2022-04-06 00:40:39,light rain
41,41,Rikitea,-23.1203,-134.9692,79.18,66,87,16.69,PF,2022-04-06 00:40:39,overcast clouds

In [19]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                214
City                   214
Lat                    214
Lng                    214
Max Temp               214
Humidity               214
Cloudiness             214
Wind Speed             214
Country                214
Date                   214
Current Description    214
dtype: int64

In [20]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
6,6,La Palma,33.8464,-118.0467,86.67,65,0,10.36,US,2022-04-06 00:40:29,clear sky
14,14,The Valley,18.2170,-63.0578,78.82,76,17,17.78,AI,2022-04-06 00:40:31,few clouds
15,15,Maragogi,-9.0122,-35.2225,77.32,84,66,4.54,BR,2022-04-06 00:40:03,broken clouds
16,16,Qui Nhon,13.7667,109.2333,76.17,80,100,19.26,VN,2022-04-06 00:40:31,overcast clouds
22,22,Puerto Ayora,-0.7393,-90.3518,78.06,86,25,7.09,EC,2022-04-06 00:40:33,scattered clouds
...,...,...,...,...,...,...,...,...,...,...,...
650,650,Boyolangu,-8.1181,111.8935,79.81,81,78,3.53,ID,2022-04-06 00:57:59,broken clouds
651,651,Jenjarom,2.8766,101.4988,78.91,85,44,2.64,MY,2022-04-06 00:57:59,scattered clouds
653,653,Yeppoon,-23.1333,150.7333,82.18,66,2,13.15,AU,2022-04-06 00:58:00,clear sky
654,654,Pochutla,15.7432,-96.4661,79.83,65,0,6.08,MX,2022-04-06 00:58:00,clear sky
658,658,Sokoni,-6.4333,39.5500,82.89,71,6,6.82,TZ,2022-04-06 00:58:02,clear sky

In [21]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,La Palma,US,86.67,clear sky,33.8464,-118.0467,
14,The Valley,AI,78.82,few clouds,18.2170,-63.0578,
15,Maragogi,BR,77.32,broken clouds,-9.0122,-35.2225,
16,Qui Nhon,VN,76.17,overcast clouds,13.7667,109.2333,
22,Puerto Ayora,EC,78.06,scattered clouds,-0.7393,-90.3518,
28,Kaeo,NZ,79.32,few clouds,-35.1000,173.7833,
32,Poum,NC,80.53,moderate rain,-20.2333,164.0167,
36,Sarh,TD,83.52,overcast clouds,9.1429,18.3923,
40,Isangel,VU,84.31,light rain,-19.5500,169.2667,
41,Rikitea,PF,79.18,overcast clouds,-23.1203,-134.9692,

In [22]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [23]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df[hotel_df["Hotel Name"].astype(bool)]
clean_hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,La Palma,US,86.67,clear sky,33.8464,-118.0467,La Quinta Inn & Suites by Wyndham Buena Park
14,The Valley,AI,78.82,few clouds,18.2170,-63.0578,CeBlue Villas & Beach Resort
15,Maragogi,BR,77.32,broken clouds,-9.0122,-35.2225,Salinas do Maragogi All Inclusive Resort
16,Qui Nhon,VN,76.17,overcast clouds,13.7667,109.2333,Khách sạn Hải Âu Quy Nhơn - Seagull Hotel
22,Puerto Ayora,EC,78.06,scattered clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
28,Kaeo,NZ,79.32,few clouds,-35.1000,173.7833,Bushido Lodge
36,Sarh,TD,83.52,overcast clouds,9.1429,18.3923,Domicile 1sur le goudron
40,Isangel,VU,84.31,light rain,-19.5500,169.2667,Tanna Lodge
41,Rikitea,PF,79.18,overcast clouds,-23.1203,-134.9692,People ThankYou
43,Katherine,AU,86.32,clear sky,-14.4667,132.2667,Pine Tree Motel
47,Hilo,US,78.53,overcast clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
52,Faanui,PF,82.92,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
56,Saint-Philippe,RE,75.22,light rain,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
64,Arlit,NE,86.20,overcast clouds,18.7369,7.3853,Case de Passage De la Prefecture
65,Kumo,NG,84.99,scattered clouds,10.0447,11.2122,Ajegunle Lodge(corpers Lodge)
67,Cabo San Lucas,MX,75.61,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
69,Meulaboh,ID,77.77,overcast clouds,4.1363,96.1285,Kost Pria
72,Arraial Do Cabo,BR,76.53,clear sky,-22.9661,-42.0278,Pousada Porto Praia
75,Kapaa,US,78.78,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
79,Vaini,TO,77.16,light intensity shower rain,-21.2000,-175.2000,Keleti Beach Resort

In [24]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [25]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [26]:
# 11a. Add a marker layer for each city to the map. 
locations =clean_hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))